### ISSUE TITLE
allow passing in an unbox function

### ISSUE THREAD

**Issue by mmckegg** [flumedb/flumeview-query#5]
It would be nice to be able to use `flumeview-query/links` against private messages also.

Could be supported by adding the ability to pass an unbox function in that would be used to decode any encrypted messages.

In the ssbc/ssb-backlinks fork of `links`, I just [whacked an `unbox` option on the constructor](https://github.com/ssbc/ssb-backlinks/blob/master/lib/flumeview-links-raw.js#L15), but this isn't very nice. Maybe an options argument would do the trick?

https://github.com/ssbc/ssb-backlinks/blob/master/lib/flumeview-links-raw.js#L36-L38

This would help close ssbc/ssb-backlinks#4

**Comment by dominictarr** [comment]
the unbox method is very ssb specific, it would be acceptable if it was a generic function that synchronously transformed the record before looking up the indexes. (because this is a flume thing, and flume doesn't know about ssb)

but I'm thinking that really, scuttlebutt probably wants to decrypt before any of the indexes run. So probably it should be in the log.get (which is actually an easy place to put it, it could even be async - which may be needed for some `private-groups`... then the apis that you don't want to retrive the raw encrypted messages are actually the exception: replication basically.

Except in the case of web viewers, they would be a bit of a footgun but it would only effect messages that are encrypted to the pub. That isn't such a big issue.

**Comment by arj03** [comment]
With secure-scuttlebutt 18 this should no longer be a problem.
